# Generated by Django 4.2.7 on 2023-11-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_img', models.ImageField(upload_to='pics')),
                ('team_name', models.CharField(max_length=250)),
                ('team_disc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
